---
title: "\\vspace{-2cm} Stat 405 Final"
author: "Meera Borle, Isis Burgos, Naomi Consiglio, Carson Foster, Aidan Gerber"
date: "December 10th, 2022"
fontsize: 12pt
geometry: margin=1in
mainfont: Times New Roman
colorlinks: yes
output:
  pdf_document:
    default
  prettydoc::html_pretty:
    toc: yes
    toc_depth: 3
    theme: hpstr
    highlight: tango
    df_print: paged
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
header-includes: \usepackage{setspace}
---
\doublespacing
```{r setup, include=FALSE}
options(scipen = 999)
options(digits = 2)
# for PDF full
# knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, dev = 'png')
# SHOW_BACK_TO_TOP=FALSE
# for PDF no code
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, dev = "png", results = "hide", out.width = "100%", fig.align = "center", dpi = 300)
SHOW_BACK_TO_TOP <- FALSE
# for html with svg
# knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, dev = 'svglite', out.width="100%")
# SHOW_BACK_TO_TOP=TRUE
```

```{r imports}
library(tidyverse)
library(RSQLite)
```

```{r include-db, include = FALSE}
db <- dbConnect(SQLite(), "data/mortality.sqlite")
query <- function(q) {
    req <- dbSendQuery(db, q)
    results <- dbFetch(req)
    dbClearResult(req)
    results
}
```
# Introduction

```{r disconnect-db, include = FALSE}
dbDisconnect(db)
```