---
title: Stat 405 Mortality
author: Meera Borle, Isis Burgos, Naomi Consiglio, Carson Foster, Aidan Gerber
date: November 23, 2022
output:
    ioslides_presentation:
        widescreen: true
---
```{r setup, include=FALSE}
source("setup.r")
```

# Data

## Data Introduction

## Secondary Dataset

# Questions

## Given someone is dead, how did they die?

## Hypothesis + More Questions

# Exploration & Methods

---

```{r, weekday_deaths, fig.cap="caption", echo=FALSE}
source("plots/weekday_deaths.r", local = TRUE, print.eval = TRUE)
deaths_by_day_plot()
```

---

```{r weekday_deaths_scaled, fig.cap="caption", echo=FALSE}
deaths_by_day_plot_scaled()
```

---

```{r, months_deaths, fig.cap="caption", echo=FALSE}
source("plots/month_count.r", local = TRUE, print.eval = TRUE)
```

---

```{r, educ_cause, echo=FALSE, fig.width=10, fig.height = 6}
source("plots/educ_cause.r", local = TRUE, print.eval = TRUE)
plot_educ_cause()
```

## Table {.smaller}

```{r, educ_cause_table, echo=FALSE}
educ_cause_table()
```

---

```{r, killer, fig.cap="caption", echo=FALSE}
source("plots/killer.r", local = TRUE, print.eval = TRUE)

draw_killer(person_colors)
```

# Analysis

---

```{r, cancer, fig.cap="caption", echo=FALSE}
source("plots/cancer.r", local = TRUE, print.eval = TRUE)
```


